name: update-wordlist

on:
  push:
  #schedule:
  #  - cron: '*/15 * * * *'

jobs:
  update-wordlist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        
      - name: run wordlist_creator.py
        run: python3 ./wordlist_creator.py
        env:
          WORDNIK_API_KEY: ${{ secrets.WORDNIK_API_KEY }}
      
      - name: run clean_wordlist.py
        run: python3 ./clean_wordlist.py
      
      - name: run profanity_checker.py
        run: python3 ./profanity_checker.py
        env:
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated wordlist.txt with new words.
          commit_user_name: adambirds
          commit_user_email: adam.birds@adbwebdesigns.co.uk